### ISSUE TITLE
Docs for query states that `cache-and-network` can be used

### ISSUE THREAD

**Issue by neilff** [apollographql/core-docs#309]
This [piece of code](https://github.com/apollographql/apollo-client/blob/master/src/ApolloClient.ts#L342-L346) states that `cache-and-network` cannot be used.

However, the docs imply that it can be used:

![image](https://user-images.githubusercontent.com/3271978/28440280-8e9f385c-6d73-11e7-8e0e-44343e76bafb.png)

**Comment by theadactyl** [comment]
Closing this issue because the code for core docs has moved to [https://github.com/apollographql/apollo-client/tree/master/docs](https://github.com/apollographql/apollo-client/tree/master/docs)

See it live here:[https://www.apollographql.com/docs/react/](https://www.apollographql.com/docs/react/).

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
