### ISSUE TITLE
broken link in docs

### ISSUE THREAD

**Issue by SimonVuong** [apollographql/core-docs#322]
https://www.codetours.xyz/tour/xavcz/meteor-apollo-codetour is broken in the meteor apollo docs

**Comment by theadactyl** [comment]
Closing this issue because the code for core docs has moved to [https://github.com/apollographql/apollo-client/tree/master/docs](https://github.com/apollographql/apollo-client/tree/master/docs)

See it live here:[https://www.apollographql.com/docs/react/](https://www.apollographql.com/docs/react/).

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
